export const SET_LANGUAGE = 'SET_LANGUAGE';
export const CHANGE_TMP = 'CHANGE_TMP';
export const SET_PLAYER_NAME = 'SET_PLAYER_NAME';
export const CHANGE_INFO_TEXT = 'CHANGE_INFO_TEXT';
export const SET_ACTIVE_PLAYER_ID = 'SET_ACTIVE_PLAYER_ID';
export const SET_PLAYERS_VALUE = 'SET_PLAYERS_VALUE';
export const SET_CELL_BACKGROUND = 'SET_CELL_BACKGROUND';
export const SET_CELL_CLICK_COUNT = 'SET_CELL_CLICK_COUNT';
export const SET_CLICK_ENABLED = 'SET_CLICK_ENABLED';
export const SET_CELLS_BG_VALUES = 'SET_CELLS_BG_VALUES';
export const SET_TIMER_ENABLED = 'SET_TIMER_ENABLED';
export const SET_TIMER_VALUES = 'SET_TIMER_VALUES';
export const SHOW_GAMES_LIST = 'SHOW_GAMES_LIST';
export const SET_TEMP_VALUE = 'SET_TEMP_VALUE';
export const GET_LIST_FROM_FIRE_BASE = 'GET_LIST_FROM_FIRE_BASE';
export const SET_FIREBASE_WINNER_INFO = 'SET_FIREBASE_WINNER_INFO';
export const RESET_PLAYER_DATA = 'RESET_PLAYER_DATA';
export const CLEAR_TIMER = 'CLEAR_TIMER';
export const CLEAR_LIST_FIRE_BASE = 'CLEAR_LIST_FIRE_BASE';


