export const SET_LANGUAGE = 'SET_LANGUAGE';

export const SET_PLAYER_NAME = 'SET_PLAYER_NAME';
export const CHANGE_INFO_TEXT = 'CHANGE_INFO_TEXT';
export const SET_ACTIVE_PLAYER_ID = 'SET_ACTIVE_PLAYER_ID';
export const SET_PLAYERS_VALUE = 'SET_PLAYERS_VALUE';
export const SET_CELL_BACKGROUND = 'SET_CELL_BACKGROUND';
export const SET_CELL_CLICK_COUNT = 'SET_CELL_CLICK_COUNT';
export const SET_CLICK_ENABLED = 'SET_CLICK_ENABLED';
export const SET_CELL_COLVALUE = 'SET_CELL_COLVALUE';
export const SET_TIMER_ENABLED = 'SET_TIMER_ENABLED';
export const SET_TIMER_VALUES = 'SET_TIMER_VALUES';
export const SHOW_GAMES_LIST = 'SHOW_GAMES_LIST';
export const SET_TEMP_VALUE = 'SET_TEMP_VALUE';
export const GET_LIST_FROM_FIRE_BASE = 'GET_LIST_FROM_FIRE_BASE';
export const SET_FIREBASE_WINNER_INFO = 'SET_FIREBASE_WINNER_INFO';